Imports System.Collections.Generic
Imports System

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace DXWebApplication3.Models

	Partial Public Class ProductReport
		Public Property CategoryName() As String
		Public Property ProductName() As String
		Public Property ProductSales() As Decimal?
		Public Property ShippedDate() As Date?
	End Class
End Namespace
